### ISSUE TITLE
In production problem page is blank 

### ISSUE THREAD

**Issue by kiranbhanushali** [kiranbhanushali/Bytecoder---A-Online-Coding-System#11]
@jacker0031

**Comment by jacker0031** [comment]
This issue is relatated to backend part some time problemmeta is come and
some time it is not come

**Comment by jacker0031** [comment]
And also without anysubmission we don't have submission object

**Comment by kiranbhanushali** [comment]
try adding  condition when  meta is null then it shows default value .

**Comment by jacker0031** [comment]
Ok, I will check. And if I am not able to solve I will contact you

**Comment by kiranbhanushali** [comment]
okay
